name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: get npm
      run: sudo apt install npm
    - name: get angular
      run: sudo npm i -g @angular/cli
    - name: check folder
      run: ls
    - name: build
      run: ng build --prod
